<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>doublets</AssemblyName>
    <Description>CLI Interface for LinksPlatform's Platform.Data.Doublets</Description>
    <Copyright>konard, FreePhoenix888</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Platform.Data.Doublets\Platform.Data.Doublets.csproj" />
  </ItemGroup>

</Project>
